import Navbar from "@/components/Navbar/Navbar";
import ResendVerification from "@/components/Navbar/ResendVerification";
import SessionProviderClient from "@/components/SessionProviderClient";
import { auth } from "@/lib/utils/auth";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import "./styles/globals.css";

const geistSans = localFont({
  src: "./styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const circular = localFont({
  src: [
    {
      path: "./styles/fonts/CircularStd-Black.woff",
      style: "black",
    },
    {
      path: "./styles/fonts/CircularStd-Bold.woff",
      style: "bold",
    },
    {
      path: "./styles/fonts/CircularStd-Medium.woff",
      style: "medium",
    },
    {
      path: "./styles/fonts/CircularStd-Book.woff",
      style: "normal",
    },
  ],
  variable: "--font-circular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const session = await auth();

  return (
    <html
      lang="en"
      className="h-full"
      data-theme={theme?.value as "light" | "dark"}
    >
      <body
        className={`${circular.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderClient session={session}>
          <Navbar />
          {session?.user.role === "unverified" && <ResendVerification />}
          {/* <Debug /> */}
          {children}
        </SessionProviderClient>
      </body>
    </html>
  );
}
