@startuml Sequence_diagram

title Admin authorization

actor Admin
participant Server
database Database

Admin -> Server : Authentication request

group Login [Success]
  Server --> Admin : Authentication failure
else Failure
  Server --> Admin : Authentication successful

  Server -> Database : Request game statuses
  Database --> Server : Return game statuses
  
  Server --> Admin : Send game statuses and histories
end

@enduml
