@startuml Database

hide circle
skinparam linetype ortho

!define primary_key(x) <b><&key> x</b>
!define column(x) <&media-record> x

entity "users" as users {
  primary_key( id ): UUID
  --
  column( username ): text
  column( password_hash ): text
  column( email ): text
  column( apartment ): text
  column( role ): roles
}

entity "games" as games {
  primary_key( id ): serial
  --
  column( name ): text
  column( borrow_status ): borrow_statuses
  column( available_date ): timestamp
  column( image_url ): text
}

entity "borrows" as borrows {
  primary_key( id ): serial
  --
  column( borrower_id ): <<FK>> UUID
  column( game_id ): <<FK>> UUID
  column( borrow_date ): timestamp
  column( return_date ): timestamp
  column( due_date ): timestamp
}

entity "verifications" as verifications {
  primary_key( verification_key ): UUID
  --
  column( user_id ): <<FK>> UUID
  column( used ): boolean
}

enum "roles" as roles {
  unverified
  user
  admin
}

enum "borrow_statuses" as borrow_statuses {
  free
  borrowed
  late
}

users ||--o{ games
users ||-o{ verifications
games ||-o{ borrows

games -[hidden]-> roles
games -[hidden]-> borrow_statuses

@enduml
