@startuml Routers

class userRouter {
  User: createUser()
  User: updateUser()
  boolean: deleteUser()
}

class gameRouter {
  Game: borrowGame()
  Game: returnGame()
  Game: addGame()
  ..Admin tools..
  Game: updateGame()
  boolean: deleteGame()
}


@enduml