@startuml Sequence_diagram

title Game Borrowing Process

actor User
participant Server
database Database

User -> Server : Request to borrow game [Game ID]
Server -> Database : Request status of game [Game ID]
Database --> Server : Return status of game [Game ID]
Server -> Server : Check game status

group Game status [Success]
  Server -> Database : Set game [Game ID] status to borrowed
  Server -> Database : Log borrow for game [Game ID]
  Server --> User : Inform user of success\nGame [Game ID] is now borrowed
else Game is already borrowed
  Server --> User : Inform user that game [Game ID] is not available\nExpected availability: [Date]
end

@enduml
